on:
  push:
    branches: [main]
  pull_request:
name: msrv
jobs:
  check:
    runs-on: ubuntu-latest
    name: cargo check on MSRV
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.88.0
      - uses: actions/checkout@v2
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-features --all-targets
